### PR TITLE
A few little fixes

### PR DESCRIPTION
**Pull request by Desetude**

### CODE REVIEW

**Comment by oliverdunk** [comment]
Brilliant, can you reopen this on the dev branch as I don't merge straight into master :)

**Comment by Desetude** [comment]
I can't seem to find a dev branch.

**Comment by oliverdunk** [comment]
Just create it :)

**Comment by Desetude** [comment]
That would mean that it would go from my dev to your master, though.

**Comment by Desetude** [comment]
If I create it from my dev branch it will just transfer to your master, though.

**Pull request merged**
